/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Fabrica;
import Logica.IControlador;
import javax.swing.JOptionPane;
import Logica.Fecha;
import java.awt.image.BufferedImage;
import javax.swing.tree.DefaultTreeModel;
import Logica.Genero;
import java.awt.Dimension;
import java.util.Iterator;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;

/**
 *
 * @author Casca
 */
public class Main extends javax.swing.JFrame {
    
    private IControlador ICU;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setSize(550, 550);
        this.jRegisterFrame.setVisible(false);
        this.setLocationRelativeTo(null);
        
        //Inicialización
        Fabrica fabrica = Fabrica.getInstance();
        ICU = fabrica.getIControlador();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jDialog1 = new javax.swing.JDialog();
        jRegisterFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RegisterCancelButton = new javax.swing.JButton();
        RegisterAcceptButton = new javax.swing.JButton();
        jRegisterNicknameField = new javax.swing.JTextField();
        jRegisterContraseñaField = new javax.swing.JTextField();
        jRegisterEmailField = new javax.swing.JTextField();
        jRegisterNombreField = new javax.swing.JTextField();
        jRegisterApellidoField = new javax.swing.JTextField();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jComboBoxAño = new javax.swing.JComboBox<>();
        FrameNewGen = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        TreeNewGen = new javax.swing.JTree();
        bAddNewGen = new javax.swing.JButton();
        TFNewGen = new javax.swing.JTextField();
        bCancelNewGen = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FrameSeguirUser = new javax.swing.JInternalFrame();
        Follower = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Followed = new javax.swing.JTextField();
        followAccept = new javax.swing.JButton();
        FollowCancel = new javax.swing.JButton();
        LabelUserMail = new javax.swing.JLabel();
        FollowedLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuRegistros = new javax.swing.JMenu();
        jMenuItemRegUsu = new javax.swing.JMenuItem();
        jMenuItemCrearGen = new javax.swing.JMenuItem();
        jMenuItemCrearAlb = new javax.swing.JMenuItem();
        jMenuItemCrearLis = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemConCliente = new javax.swing.JMenuItem();
        jMenuItemConArtista = new javax.swing.JMenuItem();
        jMenuItemConAlbum = new javax.swing.JMenuItem();
        jMenuItemConLista = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemSegUsu = new javax.swing.JMenuItem();
        jMenuItemDejarDeSeguirUsu = new javax.swing.JMenuItem();
        jMenuItemGuardarFav = new javax.swing.JMenuItem();
        jMenuItemQuitarFav = new javax.swing.JMenuItem();
        jMenuListas = new javax.swing.JMenu();
        jMenuItemAgregarLista = new javax.swing.JMenuItem();
        jMenuItemQuitarLista = new javax.swing.JMenuItem();
        jMenuItemPublicarLista = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRegisterFrame.setVisible(true);

        jLabel1.setText("Nickname");

        jLabel2.setText("Contraseña");

        jLabel3.setText("Email");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Fecha de Nacimiento");

        jLabel7.setText("Imagen del usuario");

        RegisterCancelButton.setText("Cancelar");
        RegisterCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterCancelButtonMouseClicked(evt);
            }
        });

        RegisterAcceptButton.setText("Registrar");
        RegisterAcceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterAcceptButtonMouseClicked(evt);
            }
        });

        jRegisterNicknameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterNicknameFieldActionPerformed(evt);
            }
        });

        jRegisterEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterEmailFieldActionPerformed(evt);
            }
        });

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5","6","7","8","9","10","11","12","13","14","15","16","17","18", "19","20","21","22","23","24","25","26","27","28","29","30","31" }));

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12" }));

        jComboBoxAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900","1901","1902","1903","1904","1905","1906","1907","1908","1909","1910","1911","1912","1913","1914","1915","1916","1917","1918","1919","1920","1921","1922","1923","1924","1925","1926","1927","1928","1929","1930","1931","1932","1933","1934","1935","1936","1937","1938","1939","1940","1941","1942","1943","1944","1945","1946","1947","1948","1949","1950","1951","1952","1953","1954","1955","1956","1957","1958","1959","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015", "2016" }));

        javax.swing.GroupLayout jRegisterFrameLayout = new javax.swing.GroupLayout(jRegisterFrame.getContentPane());
        jRegisterFrame.getContentPane().setLayout(jRegisterFrameLayout);
        jRegisterFrameLayout.setHorizontalGroup(
            jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegisterFrameLayout.createSequentialGroup()
                .addComponent(RegisterCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterAcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jRegisterFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRegisterFrameLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jRegisterFrameLayout.createSequentialGroup()
                        .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRegisterEmailField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRegisterApellidoField)
                            .addComponent(jRegisterContraseñaField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRegisterNombreField)))
                    .addGroup(jRegisterFrameLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(jRegisterNicknameField))
                    .addGroup(jRegisterFrameLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jRegisterFrameLayout.setVerticalGroup(
            jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegisterFrameLayout.createSequentialGroup()
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegisterNicknameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegisterContraseñaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegisterEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegisterNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegisterApellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterCancelButton)
                    .addComponent(RegisterAcceptButton)))
        );

        FrameNewGen.setVisible(true);
        FrameNewGen.setVisible(false);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("General");
        TreeNewGen.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(TreeNewGen);

        bAddNewGen.setText("Agregar");
        bAddNewGen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddNewGenMouseClicked(evt);
            }
        });
        bAddNewGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddNewGenActionPerformed(evt);
            }
        });

        bCancelNewGen.setText("Cancelar");

        jLabel10.setText("Genero padre");

        jLabel11.setText("Nombre del nuevo genero");

        javax.swing.GroupLayout FrameNewGenLayout = new javax.swing.GroupLayout(FrameNewGen.getContentPane());
        FrameNewGen.getContentPane().setLayout(FrameNewGenLayout);
        FrameNewGenLayout.setHorizontalGroup(
            FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameNewGenLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(FrameNewGenLayout.createSequentialGroup()
                            .addComponent(bAddNewGen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCancelNewGen))
                        .addComponent(TFNewGen, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        FrameNewGenLayout.setVerticalGroup(
            FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameNewGenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNewGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddNewGen)
                    .addComponent(bCancelNewGen))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        FrameSeguirUser.setVisible(true);
        FrameSeguirUser.setVisible(false);

        jLabel8.setText("Usuario (Nick)");

        jLabel9.setText("Usuario al que descea seguir (Nick)");

        followAccept.setText("Aceptar");
        followAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followAcceptActionPerformed(evt);
            }
        });

        FollowCancel.setText("Cancelar");
        FollowCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FollowCancelActionPerformed(evt);
            }
        });

        LabelUserMail.setForeground(new java.awt.Color(255, 0, 51));

        FollowedLabel.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout FrameSeguirUserLayout = new javax.swing.GroupLayout(FrameSeguirUser.getContentPane());
        FrameSeguirUser.getContentPane().setLayout(FrameSeguirUserLayout);
        FrameSeguirUserLayout.setHorizontalGroup(
            FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                        .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Follower, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(Followed))
                                .addGap(2, 2, 2)
                                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelUserMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FollowedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(followAccept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(FollowCancel)
                        .addGap(49, 49, 49))))
        );
        FrameSeguirUserLayout.setVerticalGroup(
            FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Follower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelUserMail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Followed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FollowedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(followAccept)
                    .addComponent(FollowCancel))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jMenuInicio.setText("Inicio");
        jMenuBar1.add(jMenuInicio);

        jMenuRegistros.setText("Registros");
        jMenuRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrosActionPerformed(evt);
            }
        });

        jMenuItemRegUsu.setText("Registrar Usuario");
        jMenuItemRegUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemRegUsuMouseClicked(evt);
            }
        });
        jMenuItemRegUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegUsuActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemRegUsu);

        jMenuItemCrearGen.setText("Crear Genero");
        jMenuItemCrearGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearGenActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemCrearGen);

        jMenuItemCrearAlb.setText("Crear Album");
        jMenuItemCrearAlb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearAlbActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemCrearAlb);

        jMenuItemCrearLis.setText("Crear Lista de Reproduccion");
        jMenuRegistros.add(jMenuItemCrearLis);

        jMenuBar1.add(jMenuRegistros);

        jMenuConsultas.setText("Consultas");

        jMenuItemConCliente.setText("Consultar Cliente");
        jMenuConsultas.add(jMenuItemConCliente);

        jMenuItemConArtista.setText("Consultar Artista");
        jMenuConsultas.add(jMenuItemConArtista);

        jMenuItemConAlbum.setText("Consultar Album");
        jMenuConsultas.add(jMenuItemConAlbum);

        jMenuItemConLista.setText("Consultar Lista");
        jMenuConsultas.add(jMenuItemConLista);

        jMenuBar1.add(jMenuConsultas);

        jMenuUsuarios.setText("Usuarios");

        jMenuItemSegUsu.setText("Seguir Usuario");
        jMenuItemSegUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSegUsuActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemSegUsu);

        jMenuItemDejarDeSeguirUsu.setText("Dejar De Seguir Usuario");
        jMenuUsuarios.add(jMenuItemDejarDeSeguirUsu);

        jMenuItemGuardarFav.setText("Guardar Favorito");
        jMenuUsuarios.add(jMenuItemGuardarFav);

        jMenuItemQuitarFav.setText("Quitar Favorito");
        jMenuUsuarios.add(jMenuItemQuitarFav);

        jMenuBar1.add(jMenuUsuarios);

        jMenuListas.setText("Listas");

        jMenuItemAgregarLista.setText("Agregar Lista");
        jMenuListas.add(jMenuItemAgregarLista);

        jMenuItemQuitarLista.setText("Quitar Lista");
        jMenuListas.add(jMenuItemQuitarLista);

        jMenuItemPublicarLista.setText("Publicar Lista");
        jMenuListas.add(jMenuItemPublicarLista);

        jMenuBar1.add(jMenuListas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FrameSeguirUser)
                    .addComponent(jRegisterFrame))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(FrameNewGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FrameNewGen)
                    .addComponent(jRegisterFrame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FrameSeguirUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCrearAlbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearAlbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCrearAlbActionPerformed

    private void jMenuItemRegUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemRegUsuMouseClicked
        
    }//GEN-LAST:event_jMenuItemRegUsuMouseClicked

    private void jRegisterNicknameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterNicknameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterNicknameFieldActionPerformed

    private void jRegisterEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterEmailFieldActionPerformed

    private void RegisterCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterCancelButtonMouseClicked
        this.jRegisterFrame.setVisible(false);
    }//GEN-LAST:event_RegisterCancelButtonMouseClicked

    private void jMenuItemRegUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegUsuActionPerformed
        this.jRegisterFrame.setVisible(true);
        this.jRegisterNicknameField.setText("");
        this.jRegisterContraseñaField.setText("");
        this.jRegisterEmailField.setText("");
        this.jRegisterNombreField.setText("");
        this.jRegisterApellidoField.setText("");
    }//GEN-LAST:event_jMenuItemRegUsuActionPerformed

    private void RegisterAcceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterAcceptButtonMouseClicked
        String nick = this.jRegisterNicknameField.getText();
        String contraseña = this.jRegisterContraseñaField.getText();
        String email = this.jRegisterEmailField.getText();
        String nombre= this.jRegisterNombreField.getText();
        String apellido = this.jRegisterApellidoField.getText();
        int dia = this.jComboBoxDia.getSelectedIndex() + 1;
        int mes = this.jComboBoxMes.getSelectedIndex() + 1;
        int año = this.jComboBoxAño.getSelectedIndex() + 1900;
        Fecha fechaDeNac = new Fecha(dia, mes, año);
        if(fechaDeNac.validarFecha())
            System.out.println("Valida");
        else
            System.out.println("Invalida");        
        
        //A través de mi interfaz registro a un nuevo usuario en mi Sistema
        ICU.registrarUsuario(nick, contraseña, email, nombre, apellido, fechaDeNac, null); // Corresponder con los datos correctos luego
        
        //Muestro éxito de la operación
        JOptionPane.showMessageDialog(this, "El Usuario se ha creado con éxito", "Registrar Usuario", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RegisterAcceptButtonMouseClicked

    private void jMenuItemCrearGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearGenActionPerformed
        FrameNewGen.setVisible(true);
        Genero general=ICU.GetGenero();
        DefaultTreeModel model = (DefaultTreeModel)TreeNewGen.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)model.getRoot();        
        root.add(PopulateTree(general));
        model.reload();
    }//GEN-LAST:event_jMenuItemCrearGenActionPerformed
    
    private DefaultMutableTreeNode PopulateTree(Genero g){
        DefaultMutableTreeNode Nodo = new DefaultMutableTreeNode(g.getNombre());
        Iterator it=g.getHijos().iterator();
        Genero aux;
        while(it.hasNext()){
            aux=(Genero)it.next();
            DefaultMutableTreeNode NodoHijo= new DefaultMutableTreeNode(aux.getNombre());
            Nodo.add(NodoHijo);
            PopulateTree(aux);
        }
        return Nodo;
    }
    
    private void bAddNewGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddNewGenActionPerformed
//        Genero root=ICU.GetGenero();
//        TreeNewGen=new JTree((TreeNode) root);
//        
//        
//        DefaultTreeModel model=(DefaultTreeModel) TreeNewGen.getModel();
//        DefaultTreeModel SelectedNode=(DefaultTreeModel) TreeNewGen.getLastSelectedPathComponent();
    }//GEN-LAST:event_bAddNewGenActionPerformed

    private void bAddNewGenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddNewGenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bAddNewGenMouseClicked

    private void followAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followAcceptActionPerformed
        if(!(ICU.FindUser(Follower.getText()))){
            LabelUserMail.setText("Nick invalido");
        }
        if(!(ICU.FindUser(Followed.getText()))){
            FollowedLabel.setText("Nick invalido");
        }
        if((ICU.FindUser(Followed.getText()))&&(ICU.FindUser(Follower.getText()))){
            if(Follower.getText().equals(Followed.getText())){
                JOptionPane.showMessageDialog(this, "Los usuarios no pueden seguirse a si mismos", "Seguir Usuario", JOptionPane.ERROR_MESSAGE);
            }
            else{
                ICU.SeguirUsuario(Follower.getText(), Followed.getText());
                JOptionPane.showMessageDialog(this, "Operacion realicada con exito", "Seguir Usuario", JOptionPane.INFORMATION_MESSAGE);
                FrameSeguirUser.setVisible(false);
            }
        }       
    }//GEN-LAST:event_followAcceptActionPerformed

    private void FollowCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FollowCancelActionPerformed
        FrameSeguirUser.setVisible(false);
    }//GEN-LAST:event_FollowCancelActionPerformed

    private void jMenuRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRegistrosActionPerformed

    private void jMenuItemSegUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSegUsuActionPerformed
        this.Follower.setText("");
        this.Followed.setText("");
        this.LabelUserMail.setText("");
        this.FollowedLabel.setText("");
        this.FrameSeguirUser.setVisible(true);
    }//GEN-LAST:event_jMenuItemSegUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FollowCancel;
    private javax.swing.JTextField Followed;
    private javax.swing.JLabel FollowedLabel;
    private javax.swing.JTextField Follower;
    private javax.swing.JInternalFrame FrameNewGen;
    private javax.swing.JInternalFrame FrameSeguirUser;
    private javax.swing.JLabel LabelUserMail;
    private javax.swing.JButton RegisterAcceptButton;
    private javax.swing.JButton RegisterCancelButton;
    private javax.swing.JTextField TFNewGen;
    private javax.swing.JTree TreeNewGen;
    private javax.swing.JButton bAddNewGen;
    private javax.swing.JButton bCancelNewGen;
    private javax.swing.JButton followAccept;
    private javax.swing.JComboBox<String> jComboBoxAño;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemAgregarLista;
    private javax.swing.JMenuItem jMenuItemConAlbum;
    private javax.swing.JMenuItem jMenuItemConArtista;
    private javax.swing.JMenuItem jMenuItemConCliente;
    private javax.swing.JMenuItem jMenuItemConLista;
    private javax.swing.JMenuItem jMenuItemCrearAlb;
    private javax.swing.JMenuItem jMenuItemCrearGen;
    private javax.swing.JMenuItem jMenuItemCrearLis;
    private javax.swing.JMenuItem jMenuItemDejarDeSeguirUsu;
    private javax.swing.JMenuItem jMenuItemGuardarFav;
    private javax.swing.JMenuItem jMenuItemPublicarLista;
    private javax.swing.JMenuItem jMenuItemQuitarFav;
    private javax.swing.JMenuItem jMenuItemQuitarLista;
    private javax.swing.JMenuItem jMenuItemRegUsu;
    private javax.swing.JMenuItem jMenuItemSegUsu;
    private javax.swing.JMenu jMenuListas;
    private javax.swing.JMenu jMenuRegistros;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JTextField jRegisterApellidoField;
    private javax.swing.JTextField jRegisterContraseñaField;
    private javax.swing.JTextField jRegisterEmailField;
    private javax.swing.JInternalFrame jRegisterFrame;
    private javax.swing.JTextField jRegisterNicknameField;
    private javax.swing.JTextField jRegisterNombreField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
