/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Artista;
import Logica.Cliente;
import Logica.DataUsuario;
import Logica.Fabrica;
import Logica.IControlador;
import javax.swing.JOptionPane;
import Logica.Fecha;
import java.awt.image.BufferedImage;
import javax.swing.tree.DefaultTreeModel;
import Logica.Genero;
import Logica.Manejador;
import Logica.Usuario;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import java.util.Iterator;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;

/**
 *
 * @author Casca
 */
public class Main extends javax.swing.JFrame {
    
    private IControlador ICU;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setSize(550, 550);
        this.jRegisterFrame.setVisible(false);
        this.ClientList.setVisible(false);
        this.ArtistList.setVisible(false);
        this.setLocationRelativeTo(null);
        
        //Inicialización
        Fabrica fabrica = Fabrica.getInstance();
        ICU = fabrica.getIControlador();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame2 = new javax.swing.JInternalFrame();
        FileChooser = new javax.swing.JFileChooser();
        RegistrarArtista = new javax.swing.JDialog();
        RegistrarArtistaCancelButton = new javax.swing.JButton();
        RegistrarArtistaAcceptButton = new javax.swing.JButton();
        LinkWebTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        BiografiaTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        VentanaDeArtista = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        NickLabel3 = new javax.swing.JLabel();
        NombreLabel3 = new javax.swing.JLabel();
        ApellidoLabel3 = new javax.swing.JLabel();
        MailLabel3 = new javax.swing.JLabel();
        FechaLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BiografiaLabel2 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        WebLabel3 = new javax.swing.JLabel();
        VentanaDeCliente = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        NicknameLabel1 = new javax.swing.JLabel();
        NombreLabel1 = new javax.swing.JLabel();
        ApellidoLabel1 = new javax.swing.JLabel();
        MailLabel1 = new javax.swing.JLabel();
        FechaLabel1 = new javax.swing.JLabel();
        NickLabel2 = new javax.swing.JLabel();
        NombreLabel2 = new javax.swing.JLabel();
        ApellidoLabel2 = new javax.swing.JLabel();
        MailLabel2 = new javax.swing.JLabel();
        FechaLabel2 = new javax.swing.JLabel();
        jRegisterFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RegisterCancelButton = new javax.swing.JButton();
        RegisterAcceptButton = new javax.swing.JButton();
        jRegisterNicknameField = new javax.swing.JTextField();
        jRegisterApellidolField = new javax.swing.JTextField();
        jRegisterNombreField = new javax.swing.JTextField();
        jRegisterEmailField = new javax.swing.JTextField();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jComboBoxAño = new javax.swing.JComboBox<>();
        UserTypeComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ImagePathTextField = new javax.swing.JTextField();
        FrameNewGen = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        TreeNewGen = new javax.swing.JTree();
        bAddNewGen = new javax.swing.JButton();
        TFNewGen = new javax.swing.JTextField();
        bCancelNewGen = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FrameSeguirUser = new javax.swing.JInternalFrame();
        Follower = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Followed = new javax.swing.JTextField();
        followAccept = new javax.swing.JButton();
        FollowCancel = new javax.swing.JButton();
        LabelUserMail = new javax.swing.JLabel();
        FollowedLabel = new javax.swing.JLabel();
        ClientList = new javax.swing.JInternalFrame();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ConsultUserTextFIeld = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        UserListScroll = new javax.swing.JScrollPane();
        UserListUsers = new javax.swing.JPanel();
        ArtistList = new javax.swing.JInternalFrame();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ConsultUserTextFIeld1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        UserListScroll1 = new javax.swing.JScrollPane();
        UserListUsers1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuRegistros = new javax.swing.JMenu();
        jMenuItemRegUsu = new javax.swing.JMenuItem();
        jMenuItemCrearGen = new javax.swing.JMenuItem();
        jMenuItemCrearAlb = new javax.swing.JMenuItem();
        jMenuItemCrearLis = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemConCliente = new javax.swing.JMenuItem();
        jMenuItemConArtista = new javax.swing.JMenuItem();
        jMenuItemConAlbum = new javax.swing.JMenuItem();
        jMenuItemConLista = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemSegUsu = new javax.swing.JMenuItem();
        jMenuItemDejarDeSeguirUsu = new javax.swing.JMenuItem();
        jMenuItemGuardarFav = new javax.swing.JMenuItem();
        jMenuItemQuitarFav = new javax.swing.JMenuItem();
        jMenuListas = new javax.swing.JMenu();
        jMenuItemAgregarLista = new javax.swing.JMenuItem();
        jMenuItemQuitarLista = new javax.swing.JMenuItem();
        jMenuItemPublicarLista = new javax.swing.JMenuItem();

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        FileChooser.setCurrentDirectory(new java.io.File("C:\\Users"));
        FileChooser.setDialogTitle("Seleccion de imagen");
        FileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserActionPerformed(evt);
            }
        });

        RegistrarArtista.setTitle("Opciones de artista");

        RegistrarArtistaCancelButton.setText("Cancelar");
        RegistrarArtistaCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarArtistaCancelButtonMouseClicked(evt);
            }
        });

        RegistrarArtistaAcceptButton.setText("Registrar");
        RegistrarArtistaAcceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarArtistaAcceptButtonMouseClicked(evt);
            }
        });

        LinkWebTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinkWebTextFieldActionPerformed(evt);
            }
        });

        BiografiaTextArea.setColumns(20);
        BiografiaTextArea.setRows(5);
        jScrollPane2.setViewportView(BiografiaTextArea);

        jLabel2.setText("Biografia");

        jLabel11.setText("Link a sitio web");

        javax.swing.GroupLayout RegistrarArtistaLayout = new javax.swing.GroupLayout(RegistrarArtista.getContentPane());
        RegistrarArtista.getContentPane().setLayout(RegistrarArtistaLayout);
        RegistrarArtistaLayout.setHorizontalGroup(
            RegistrarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarArtistaLayout.createSequentialGroup()
                .addGroup(RegistrarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistrarArtistaCancelButton)
                    .addGroup(RegistrarArtistaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RegistrarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(RegistrarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegistrarArtistaAcceptButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(LinkWebTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        RegistrarArtistaLayout.setVerticalGroup(
            RegistrarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarArtistaLayout.createSequentialGroup()
                .addGroup(RegistrarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarArtistaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrarArtistaLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(RegistrarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LinkWebTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(44, 44, 44)
                .addGroup(RegistrarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarArtistaCancelButton)
                    .addComponent(RegistrarArtistaAcceptButton)))
        );

        jLabel19.setText("IMAGEN");

        jLabel20.setText("Nickname:");

        jLabel21.setText("Nombre:");

        jLabel22.setText("Apellido:");

        jLabel23.setText("Mail:");

        jLabel24.setText("Fecha de nacimiento:");

        NickLabel3.setText("nick");

        NombreLabel3.setText("nombre");

        ApellidoLabel3.setText("apellido");

        MailLabel3.setText("mail");

        FechaLabel3.setText("fecha");

        BiografiaLabel2.setColumns(20);
        BiografiaLabel2.setRows(5);
        jScrollPane3.setViewportView(BiografiaLabel2);

        jLabel13.setText("Biografia:");

        jLabel15.setText("Pagina web:");

        WebLabel3.setText("web");

        javax.swing.GroupLayout VentanaDeArtistaLayout = new javax.swing.GroupLayout(VentanaDeArtista.getContentPane());
        VentanaDeArtista.getContentPane().setLayout(VentanaDeArtistaLayout);
        VentanaDeArtistaLayout.setHorizontalGroup(
            VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(VentanaDeArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaDeArtistaLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaLabel3)
                            .addComponent(MailLabel3)
                            .addComponent(ApellidoLabel3)
                            .addComponent(NombreLabel3)
                            .addComponent(NickLabel3)
                            .addComponent(WebLabel3)))
                    .addComponent(jLabel13))
                .addGap(71, 104, Short.MAX_VALUE))
        );
        VentanaDeArtistaLayout.setVerticalGroup(
            VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaDeArtistaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaDeArtistaLayout.createSequentialGroup()
                        .addGroup(VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(NickLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(NombreLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(ApellidoLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(MailLabel3))
                        .addGap(7, 7, 7)
                        .addGroup(VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(FechaLabel3)))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaDeArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(WebLabel3))
                .addGap(9, 9, 9)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel33.setText("IMAGEN");

        NicknameLabel1.setText("Nickname:");

        NombreLabel1.setText("Nombre:");

        ApellidoLabel1.setText("Apellido:");

        MailLabel1.setText("Mail:");

        FechaLabel1.setText("Fecha de nacimiento:");

        NickLabel2.setText("nick");

        NombreLabel2.setText("nombre");

        ApellidoLabel2.setText("apellido");

        MailLabel2.setText("mail");

        FechaLabel2.setText("fecha");

        javax.swing.GroupLayout VentanaDeClienteLayout = new javax.swing.GroupLayout(VentanaDeCliente.getContentPane());
        VentanaDeCliente.getContentPane().setLayout(VentanaDeClienteLayout);
        VentanaDeClienteLayout.setHorizontalGroup(
            VentanaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaDeClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VentanaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NicknameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreLabel1)
                    .addComponent(MailLabel1)
                    .addComponent(FechaLabel1)
                    .addComponent(ApellidoLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaLabel2)
                    .addComponent(MailLabel2)
                    .addComponent(NombreLabel2)
                    .addComponent(NickLabel2)
                    .addComponent(ApellidoLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VentanaDeClienteLayout.setVerticalGroup(
            VentanaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaDeClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VentanaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaDeClienteLayout.createSequentialGroup()
                        .addGroup(VentanaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NicknameLabel1)
                            .addComponent(NickLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VentanaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreLabel1)
                            .addComponent(NombreLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VentanaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoLabel1)
                            .addComponent(ApellidoLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VentanaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MailLabel1)
                            .addComponent(MailLabel2))
                        .addGap(7, 7, 7)
                        .addGroup(VentanaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaLabel1)
                            .addComponent(FechaLabel2)))
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRegisterFrame.setVisible(true);

        jLabel1.setText("Nickname");

        jLabel3.setText("Email");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Fecha de nacimiento");

        jLabel7.setText("Imagen del usuario");

        RegisterCancelButton.setText("Cancelar");
        RegisterCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterCancelButtonMouseClicked(evt);
            }
        });

        RegisterAcceptButton.setText("Registrar");
        RegisterAcceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterAcceptButtonMouseClicked(evt);
            }
        });
        RegisterAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterAcceptButtonActionPerformed(evt);
            }
        });

        jRegisterNicknameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterNicknameFieldActionPerformed(evt);
            }
        });

        jRegisterApellidolField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterApellidolFieldActionPerformed(evt);
            }
        });

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5","6","7","8","9","10","11","12","13","14","15","16","17","18", "19","20","21","22","23","24","25","26","27","28","29","30","31" }));
        jComboBoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiaActionPerformed(evt);
            }
        });

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12" }));

        jComboBoxAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900","1901","1902","1903","1904","1905","1906","1907","1908","1909","1910","1911","1912","1913","1914","1915","1916","1917","1918","1919","1920","1921","1922","1923","1924","1925","1926","1927","1928","1929","1930","1931","1932","1933","1934","1935","1936","1937","1938","1939","1940","1941","1942","1943","1944","1945","1946","1947","1948","1949","1950","1951","1952","1953","1954","1955","1956","1957","1958","1959","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015", "2016" }));

        UserTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Artista" }));
        UserTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo de usuario");

        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ImagePathTextField.setEnabled(false);

        javax.swing.GroupLayout jRegisterFrameLayout = new javax.swing.GroupLayout(jRegisterFrame.getContentPane());
        jRegisterFrame.getContentPane().setLayout(jRegisterFrameLayout);
        jRegisterFrameLayout.setHorizontalGroup(
            jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegisterFrameLayout.createSequentialGroup()
                .addComponent(RegisterCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterAcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jRegisterFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRegisterFrameLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(jRegisterNicknameField))
                    .addGroup(jRegisterFrameLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(jRegisterEmailField))
                    .addGroup(jRegisterFrameLayout.createSequentialGroup()
                        .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRegisterNombreField)
                            .addComponent(jRegisterApellidolField)))
                    .addGroup(jRegisterFrameLayout.createSequentialGroup()
                        .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(jRegisterFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(UserTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jRegisterFrameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jRegisterFrameLayout.createSequentialGroup()
                                .addComponent(ImagePathTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))))))
        );
        jRegisterFrameLayout.setVerticalGroup(
            jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegisterFrameLayout.createSequentialGroup()
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegisterNicknameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegisterNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegisterApellidolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegisterEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(ImagePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(UserTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterCancelButton)
                    .addComponent(RegisterAcceptButton)))
        );

        FrameNewGen.setVisible(true);
        FrameNewGen.setVisible(false);
        FrameNewGen.setTitle("Alta Genero");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("General");
        TreeNewGen.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(TreeNewGen);

        bAddNewGen.setText("Agregar");
        bAddNewGen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddNewGenMouseClicked(evt);
            }
        });
        bAddNewGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddNewGenActionPerformed(evt);
            }
        });

        bCancelNewGen.setText("Cancelar");
        bCancelNewGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelNewGenActionPerformed(evt);
            }
        });

        jLabel10.setText("Genero padre");

        jLabel11.setText("Nombre del nuevo genero");

        javax.swing.GroupLayout FrameNewGenLayout = new javax.swing.GroupLayout(FrameNewGen.getContentPane());
        FrameNewGen.getContentPane().setLayout(FrameNewGenLayout);
        FrameNewGenLayout.setHorizontalGroup(
            FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameNewGenLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameNewGenLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TFNewGen, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(FrameNewGenLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(bAddNewGen)
                        .addGap(18, 18, 18)
                        .addComponent(bCancelNewGen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(FrameNewGenLayout.createSequentialGroup()
                            .addComponent(bAddNewGen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCancelNewGen))
                        .addComponent(TFNewGen, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        FrameNewGenLayout.setVerticalGroup(
            FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameNewGenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(FrameNewGenLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(TFNewGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddNewGen)
                    .addComponent(bCancelNewGen)))
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNewGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameNewGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddNewGen)
                    .addComponent(bCancelNewGen))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        FrameSeguirUser.setVisible(true);
        FrameSeguirUser.setVisible(false);
        FrameSeguirUser.setTitle("Seguir Usuario");

        jLabel8.setText("Usuario (Nick)");

        jLabel9.setText("Usuario al que descea seguir (Nick)");

        followAccept.setText("Aceptar");
        followAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followAcceptActionPerformed(evt);
            }
        });

        FollowCancel.setText("Cancelar");
        FollowCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FollowCancelActionPerformed(evt);
            }
        });

        LabelUserMail.setForeground(new java.awt.Color(255, 0, 51));

        FollowedLabel.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout FrameSeguirUserLayout = new javax.swing.GroupLayout(FrameSeguirUser.getContentPane());
        FrameSeguirUser.getContentPane().setLayout(FrameSeguirUserLayout);
        FrameSeguirUserLayout.setHorizontalGroup(
            FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                        .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Follower, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(Followed))
                                .addGap(2, 2, 2)
                                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelUserMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FollowedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(followAccept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(FollowCancel)
                        .addGap(49, 49, 49))))
        );
        FrameSeguirUserLayout.setVerticalGroup(
            FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameSeguirUserLayout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Follower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelUserMail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Followed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FollowedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(FrameSeguirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(followAccept)
                    .addComponent(FollowCancel))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        ClientList.setVisible(true);

        jButton2.setText("Aceptar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel12.setText("Nick del usuario a consultar");

        javax.swing.GroupLayout UserListUsersLayout = new javax.swing.GroupLayout(UserListUsers);
        UserListUsers.setLayout(UserListUsersLayout);
        UserListUsersLayout.setHorizontalGroup(
            UserListUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        UserListUsersLayout.setVerticalGroup(
            UserListUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        UserListScroll.setViewportView(UserListUsers);

        javax.swing.GroupLayout ClientListLayout = new javax.swing.GroupLayout(ClientList.getContentPane());
        ClientList.getContentPane().setLayout(ClientListLayout);
        ClientListLayout.setHorizontalGroup(
            ClientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientListLayout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(ClientListLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConsultUserTextFIeld))
            .addGroup(ClientListLayout.createSequentialGroup()
                .addComponent(UserListScroll)
                .addContainerGap())
        );
        ClientListLayout.setVerticalGroup(
            ClientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientListLayout.createSequentialGroup()
                .addComponent(UserListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ClientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultUserTextFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ClientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        ArtistList.setVisible(true);

        jButton4.setText("Aceptar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel14.setText("Nick del usuario a consultar");

        javax.swing.GroupLayout UserListUsers1Layout = new javax.swing.GroupLayout(UserListUsers1);
        UserListUsers1.setLayout(UserListUsers1Layout);
        UserListUsers1Layout.setHorizontalGroup(
            UserListUsers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        UserListUsers1Layout.setVerticalGroup(
            UserListUsers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        UserListScroll1.setViewportView(UserListUsers1);

        javax.swing.GroupLayout ArtistListLayout = new javax.swing.GroupLayout(ArtistList.getContentPane());
        ArtistList.getContentPane().setLayout(ArtistListLayout);
        ArtistListLayout.setHorizontalGroup(
            ArtistListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArtistListLayout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
            .addGroup(ArtistListLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConsultUserTextFIeld1))
            .addGroup(ArtistListLayout.createSequentialGroup()
                .addComponent(UserListScroll1)
                .addContainerGap())
        );
        ArtistListLayout.setVerticalGroup(
            ArtistListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArtistListLayout.createSequentialGroup()
                .addComponent(UserListScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ArtistListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultUserTextFIeld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ArtistListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)))
        );

        jMenuInicio.setText("Inicio");
        jMenuBar1.add(jMenuInicio);

        jMenuRegistros.setText("Registros");
        jMenuRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrosActionPerformed(evt);
            }
        });

        jMenuItemRegUsu.setText("Registrar Usuario");
        jMenuItemRegUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemRegUsuMouseClicked(evt);
            }
        });
        jMenuItemRegUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegUsuActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemRegUsu);

        jMenuItemCrearGen.setText("Crear Genero");
        jMenuItemCrearGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearGenActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemCrearGen);

        jMenuItemCrearAlb.setText("Crear Album");
        jMenuItemCrearAlb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearAlbActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuItemCrearAlb);

        jMenuItemCrearLis.setText("Crear Lista de Reproduccion");
        jMenuRegistros.add(jMenuItemCrearLis);

        jMenuBar1.add(jMenuRegistros);

        jMenuConsultas.setText("Consultas");

        jMenuItemConCliente.setText("Consultar Cliente");
        jMenuItemConCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemConClienteMouseClicked(evt);
            }
        });
        jMenuItemConCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConClienteActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemConCliente);

        jMenuItemConArtista.setText("Consultar Artista");
        jMenuItemConArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemConArtistaMouseClicked(evt);
            }
        });
        jMenuItemConArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConArtistaActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemConArtista);

        jMenuItemConAlbum.setText("Consultar Album");
        jMenuConsultas.add(jMenuItemConAlbum);

        jMenuItemConLista.setText("Consultar Lista");
        jMenuConsultas.add(jMenuItemConLista);

        jMenuBar1.add(jMenuConsultas);

        jMenuUsuarios.setText("Usuarios");

        jMenuItemSegUsu.setText("Seguir Usuario");
        jMenuItemSegUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSegUsuActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemSegUsu);

        jMenuItemDejarDeSeguirUsu.setText("Dejar De Seguir Usuario");
        jMenuUsuarios.add(jMenuItemDejarDeSeguirUsu);

        jMenuItemGuardarFav.setText("Guardar Favorito");
        jMenuUsuarios.add(jMenuItemGuardarFav);

        jMenuItemQuitarFav.setText("Quitar Favorito");
        jMenuUsuarios.add(jMenuItemQuitarFav);

        jMenuBar1.add(jMenuUsuarios);

        jMenuListas.setText("Listas");

        jMenuItemAgregarLista.setText("Agregar Lista");
        jMenuListas.add(jMenuItemAgregarLista);

        jMenuItemQuitarLista.setText("Quitar Lista");
        jMenuListas.add(jMenuItemQuitarLista);

        jMenuItemPublicarLista.setText("Publicar Lista");
        jMenuListas.add(jMenuItemPublicarLista);

        jMenuBar1.add(jMenuListas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FrameSeguirUser)
                    .addComponent(jRegisterFrame))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(FrameNewGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jRegisterFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FrameNewGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(ClientList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FrameSeguirUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ArtistList)
                    .addGap(306, 306, 306)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FrameNewGen)
                    .addComponent(jRegisterFrame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegisterFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClientList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(FrameNewGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FrameSeguirUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ArtistList)
                    .addContainerGap(391, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCrearAlbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearAlbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCrearAlbActionPerformed

    private void jMenuItemRegUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemRegUsuMouseClicked
        
    }//GEN-LAST:event_jMenuItemRegUsuMouseClicked

    private void jRegisterNicknameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterNicknameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterNicknameFieldActionPerformed

    private void jRegisterApellidolFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterApellidolFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterApellidolFieldActionPerformed

    private void RegisterCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterCancelButtonMouseClicked
        this.jRegisterFrame.setVisible(false);
    }//GEN-LAST:event_RegisterCancelButtonMouseClicked

    private void jMenuItemRegUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegUsuActionPerformed
        this.jRegisterFrame.setVisible(true);
        this.jRegisterNicknameField.setText("");
        this.jRegisterApellidolField.setText("");
        this.jRegisterNombreField.setText("");
        this.jRegisterEmailField.setText("");
    }//GEN-LAST:event_jMenuItemRegUsuActionPerformed

    private void RegisterAcceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterAcceptButtonMouseClicked
        String nick = this.jRegisterNicknameField.getText();
        String apellido = this.jRegisterApellidolField.getText();
        String nombre= this.jRegisterNombreField.getText();
        String email = this.jRegisterEmailField.getText();
        int userTypeIndex = this.UserTypeComboBox.getSelectedIndex();
        String userType = this.UserTypeComboBox.getItemAt(userTypeIndex);
        int dia = this.jComboBoxDia.getSelectedIndex() + 1;
        int mes = this.jComboBoxMes.getSelectedIndex() + 1;
        int año = this.jComboBoxAño.getSelectedIndex() + 1900;
        Fecha fechaDeNac = new Fecha(dia, mes, año);
        if(fechaDeNac.validarFecha()){
            if(!nick.isEmpty() && !email.isEmpty() && !nombre.isEmpty() &&
                    !apellido.isEmpty()){
               if(userType=="Cliente"){
                    if(ICU.nicknameLibre(nick)){
                        if(ICU.mailLibre(email)){
                            ICU.registrarUsuario(nick, "", email, nombre, apellido, fechaDeNac, null, userType, "", "");
                            JOptionPane.showMessageDialog(this, "El Cliente se ha creado con éxito", "Registrar Usuario", JOptionPane.INFORMATION_MESSAGE);                
                            return;   
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Email en uso", "Error", JOptionPane.INFORMATION_MESSAGE); 
                            return; 
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Nickname en uso", "Error", JOptionPane.INFORMATION_MESSAGE); 
                        return;
                    }     
                    
            }
                if(userType=="Artista")      
                    if(ICU.nicknameLibre(nick)){
                        if(ICU.mailLibre(email)){
                            this.RegistrarArtista.setSize(500, 500);
                            this.RegistrarArtista.setVisible(true);
                        }
                        else
                            JOptionPane.showMessageDialog(this, "Email en uso", "Error", JOptionPane.INFORMATION_MESSAGE); 
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Nickname en uso", "Error", JOptionPane.INFORMATION_MESSAGE);
                    }
                     
            }
            else
               JOptionPane.showMessageDialog(this, "Todos los campos son necesarios", "Error", JOptionPane.INFORMATION_MESSAGE); 
            
        }
        else
            JOptionPane.showMessageDialog(this, "Fecha invalida", "Error", JOptionPane.INFORMATION_MESSAGE);       
        
        
        //A través de mi interfaz registro a un nuevo usuario en mi Sistema
        
        
        //Muestro éxito de la operación
        
    }//GEN-LAST:event_RegisterAcceptButtonMouseClicked

    private void jMenuItemCrearGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearGenActionPerformed
        FrameNewGen.setVisible(true);
        PopulateTree();
    }//GEN-LAST:event_jMenuItemCrearGenActionPerformed
    
    private void PopulateTree(){        
        //No tocar ¡chanchada!
        TreeNewGen = new javax.swing.JTree();
        DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("General");
        TreeNewGen.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(TreeNewGen);
        ////////////////////////////////////////////////////////////////////////
        
        Genero general=ICU.GetGenero();
        DefaultTreeModel model = (DefaultTreeModel)TreeNewGen.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)model.getRoot();
        Iterator it = general.getHijos().iterator();
        while(it.hasNext()){
            root.add(RecursivePopulate((Genero)it.next()));
        }
        model.reload(root);
        TreeNewGen.revalidate();
    }
    
    private DefaultMutableTreeNode RecursivePopulate(Genero g){
        DefaultMutableTreeNode nodo= new DefaultMutableTreeNode(g.getNombre());
        Iterator it=g.getHijos().iterator();
        Genero aux;
        while(it.hasNext()){
            aux=(Genero)it.next();
            nodo.add(RecursivePopulate(aux));
        }
        return nodo;
    }
    
    private void bAddNewGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddNewGenActionPerformed
        if(!(TFNewGen.getText().equals(""))){
            DefaultMutableTreeNode select = (DefaultMutableTreeNode) TreeNewGen.getLastSelectedPathComponent();
            String SelectedNom;
            if(select!=null)
                SelectedNom=select.toString();
            else
                SelectedNom="";
            ICU.AltaGenero(TFNewGen.getText(), SelectedNom);
            PopulateTree();
        }
    }//GEN-LAST:event_bAddNewGenActionPerformed

    private void bAddNewGenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddNewGenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bAddNewGenMouseClicked

    private void followAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followAcceptActionPerformed
        if(!(ICU.FindUser(Follower.getText()))){
            LabelUserMail.setText("Nick invalido");
        }
        if(!(ICU.FindUser(Followed.getText()))){
            FollowedLabel.setText("Nick invalido");
        }
        if((ICU.FindUser(Followed.getText()))&&(ICU.FindUser(Follower.getText()))){
            if(Follower.getText().equals(Followed.getText())){
                JOptionPane.showMessageDialog(this, "Los usuarios no pueden seguirse a si mismos", "Seguir Usuario", JOptionPane.ERROR_MESSAGE);
            }
            else{
                ICU.SeguirUsuario(Follower.getText(), Followed.getText());
                JOptionPane.showMessageDialog(this, "Operacion realicada con exito", "Seguir Usuario", JOptionPane.INFORMATION_MESSAGE);
                FrameSeguirUser.setVisible(false);
            }
        }       
    }//GEN-LAST:event_followAcceptActionPerformed

    private void FollowCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FollowCancelActionPerformed
        FrameSeguirUser.setVisible(false);
    }//GEN-LAST:event_FollowCancelActionPerformed

    private void jMenuRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRegistrosActionPerformed

    private void jMenuItemSegUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSegUsuActionPerformed
        this.Follower.setText("");
        this.Followed.setText("");
        this.LabelUserMail.setText("");
        this.FollowedLabel.setText("");
        this.FrameSeguirUser.setVisible(true);
    }//GEN-LAST:event_jMenuItemSegUsuActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.FileChooser.showOpenDialog(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDiaActionPerformed

    private void RegisterAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterAcceptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterAcceptButtonActionPerformed

    private void LinkWebTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinkWebTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LinkWebTextFieldActionPerformed
                            
    private void RegistrarArtistaCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarArtistaCancelButtonMouseClicked
    this.RegistrarArtista.setVisible(false); 
    }//GEN-LAST:event_RegistrarArtistaCancelButtonMouseClicked

    private void RegistrarArtistaAcceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarArtistaAcceptButtonMouseClicked
        String nick = this.jRegisterNicknameField.getText();
        String email = this.jRegisterApellidolField.getText();
        String nombre= this.jRegisterNombreField.getText();
        String apellido = this.jRegisterEmailField.getText();
        int userTypeIndex = this.UserTypeComboBox.getSelectedIndex();
        String userType = this.UserTypeComboBox.getItemAt(userTypeIndex);
        int dia = this.jComboBoxDia.getSelectedIndex() + 1;
        int mes = this.jComboBoxMes.getSelectedIndex() + 1;
        int año = this.jComboBoxAño.getSelectedIndex() + 1900;
        Fecha fechaDeNac = new Fecha(dia, mes, año);
        String biografia = this.BiografiaTextArea.getText();
        String website = this.LinkWebTextField.getText();
        
        ICU.registrarUsuario(nick, "", email, nombre, apellido, fechaDeNac, null, userType, biografia, website);
        this.BiografiaTextArea.setText("");
        this.LinkWebTextField.setText("");
        this.RegistrarArtista.setVisible(false);
        JOptionPane.showMessageDialog(this, "El Artista se ha creado con éxito", "Registrar Usuario", JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_RegistrarArtistaAcceptButtonMouseClicked

    private void jMenuItemConClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemConClienteMouseClicked
     
    }//GEN-LAST:event_jMenuItemConClienteMouseClicked

    private void jMenuItemConArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemConArtistaMouseClicked
      
    }//GEN-LAST:event_jMenuItemConArtistaMouseClicked

    private void jMenuItemConClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConClienteActionPerformed
        //Relevar esto al controlador
        this.ClientList.setSize(500, 500);
        Manejador manejador = Logica.Manejador.getinstance();
        List<Cliente> clientes = manejador.getClientes();
        int numeroDeClientes = clientes.size();  
        for(int i=0; i<numeroDeClientes; i++){
            JLabel label = new JLabel();
            label.setText(clientes.get(i).getNickname());
            label.setBounds(0, 40*i, 200, 40);
            this.UserListUsers.add(label);              
        }    
        this.ClientList.setVisible(true);
    }//GEN-LAST:event_jMenuItemConClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        this.ClientList.setVisible(false);
        this.UserListUsers.removeAll();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String username = this.ConsultUserTextFIeld.getText();
        if(!username.isEmpty()){
            Cliente user = ICU.consultarCliente(username);   
            if(!(user==null)){ //Si encuentra al usuario
                Fecha fecha = user.getFechaDeNacimiento();
                String fechaString = String.valueOf(fecha.getDia()) + '/' + String.valueOf(fecha.getMes()) + '/' + String.valueOf(fecha.getAño());
                //DataUsuario usuario = ICU.ConsultarCliente(username);                
                this.NickLabel2.setText(username);
                this.NombreLabel2.setText(user.getNombre());
                this.ApellidoLabel2.setText(user.getApellido());
                this.MailLabel2.setText(user.getMail());
                this.FechaLabel2.setText(fechaString);
                this.VentanaDeCliente.setSize(500, 200);
                this.VentanaDeCliente.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(this, "No existe el usuario", "Consultar Cliente", JOptionPane.INFORMATION_MESSAGE);
                
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void UserTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTypeComboBoxActionPerformed
        String type = this.UserTypeComboBox.getSelectedItem().toString();
        if(type.equals("Cliente")){
            this.RegisterAcceptButton.setText("Registrar");
        }
        else
            this.RegisterAcceptButton.setText("Siguiente");
    }//GEN-LAST:event_UserTypeComboBoxActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String username = this.ConsultUserTextFIeld1.getText();
        if(!username.isEmpty()){
            Artista user = ICU.consultarArtista(username);   
            if(!(user==null)){ //Si encuentra al usuario
                Fecha fecha = user.getFechaDeNacimiento();
                String fechaString = String.valueOf(fecha.getDia()) + '/' + String.valueOf(fecha.getMes()) + '/' + String.valueOf(fecha.getAño());
                //DataUsuario usuario = ICU.ConsultarCliente(username);                
                this.NickLabel3.setText(username);
                this.NombreLabel3.setText(user.getNombre());
                this.ApellidoLabel3.setText(user.getApellido());
                this.MailLabel3.setText(user.getMail());
                this.FechaLabel3.setText(fechaString);
                this.BiografiaLabel2.setText(user.getBiografia());
                this.WebLabel3.setText(user.getDir_web());
                this.VentanaDeArtista.setSize(500, 200);
                this.VentanaDeArtista.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(this, "No existe el usuario", "Consultar Artista", JOptionPane.INFORMATION_MESSAGE);
                
        }
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        this.ArtistList.setVisible(false);
        this.UserListUsers1.removeAll();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jMenuItemConArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConArtistaActionPerformed
        this.ArtistList.setSize(500, 500);               
        Manejador manejador = Logica.Manejador.getinstance();
        List<Artista> artistas = manejador.getArtistas();
        int numeroDeArtistas = artistas.size();  
        for(int i=0; i<numeroDeArtistas; i++){
            JLabel label = new JLabel();
            label.setText(artistas.get(i).getNickname());
            label.setBounds(0, 40*i, 200, 40);
            this.UserListUsers1.add(label);              
        }    
        this.ArtistList.setVisible(true);
    }//GEN-LAST:event_jMenuItemConArtistaActionPerformed

    private void FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserActionPerformed
        int returnVal = this.FileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = this.FileChooser.getSelectedFile();
            try {
                //What to do with the file, e.g. display it in a TextArea
                this.ImagePathTextField.read( new FileReader( file.getAbsolutePath() ), null );
        } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_FileChooserActionPerformed

    
    private void bCancelNewGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelNewGenActionPerformed
        FrameNewGen.setVisible(false);
        TFNewGen.setText("");
    }//GEN-LAST:event_bCancelNewGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoLabel1;
    private javax.swing.JLabel ApellidoLabel2;
    private javax.swing.JLabel ApellidoLabel3;
    private javax.swing.JInternalFrame ArtistList;
    private javax.swing.JTextArea BiografiaLabel2;
    private javax.swing.JTextArea BiografiaTextArea;
    private javax.swing.JInternalFrame ClientList;
    private javax.swing.JTextField ConsultUserTextFIeld;
    private javax.swing.JTextField ConsultUserTextFIeld1;
    private javax.swing.JLabel FechaLabel1;
    private javax.swing.JLabel FechaLabel2;
    private javax.swing.JLabel FechaLabel3;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JButton FollowCancel;
    private javax.swing.JTextField Followed;
    private javax.swing.JLabel FollowedLabel;
    private javax.swing.JTextField Follower;
    private javax.swing.JInternalFrame FrameNewGen;
    private javax.swing.JInternalFrame FrameSeguirUser;
    private javax.swing.JTextField ImagePathTextField;
    private javax.swing.JLabel LabelUserMail;
    private javax.swing.JTextField LinkWebTextField;
    private javax.swing.JLabel MailLabel1;
    private javax.swing.JLabel MailLabel2;
    private javax.swing.JLabel MailLabel3;
    private javax.swing.JLabel NickLabel2;
    private javax.swing.JLabel NickLabel3;
    private javax.swing.JLabel NicknameLabel1;
    private javax.swing.JLabel NombreLabel1;
    private javax.swing.JLabel NombreLabel2;
    private javax.swing.JLabel NombreLabel3;
    private javax.swing.JButton RegisterAcceptButton;
    private javax.swing.JButton RegisterCancelButton;
    private javax.swing.JDialog RegistrarArtista;
    private javax.swing.JButton RegistrarArtistaAcceptButton;
    private javax.swing.JButton RegistrarArtistaCancelButton;
    private javax.swing.JTextField TFNewGen;
    private javax.swing.JTree TreeNewGen;
    private javax.swing.JScrollPane UserListScroll;
    private javax.swing.JScrollPane UserListScroll1;
    private javax.swing.JPanel UserListUsers;
    private javax.swing.JPanel UserListUsers1;
    private javax.swing.JComboBox<String> UserTypeComboBox;
    private javax.swing.JDialog VentanaDeArtista;
    private javax.swing.JDialog VentanaDeCliente;
    private javax.swing.JLabel WebLabel3;
    private javax.swing.JButton bAddNewGen;
    private javax.swing.JButton bCancelNewGen;
    private javax.swing.JButton followAccept;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBoxAño;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemAgregarLista;
    private javax.swing.JMenuItem jMenuItemConAlbum;
    private javax.swing.JMenuItem jMenuItemConArtista;
    private javax.swing.JMenuItem jMenuItemConCliente;
    private javax.swing.JMenuItem jMenuItemConLista;
    private javax.swing.JMenuItem jMenuItemCrearAlb;
    private javax.swing.JMenuItem jMenuItemCrearGen;
    private javax.swing.JMenuItem jMenuItemCrearLis;
    private javax.swing.JMenuItem jMenuItemDejarDeSeguirUsu;
    private javax.swing.JMenuItem jMenuItemGuardarFav;
    private javax.swing.JMenuItem jMenuItemPublicarLista;
    private javax.swing.JMenuItem jMenuItemQuitarFav;
    private javax.swing.JMenuItem jMenuItemQuitarLista;
    private javax.swing.JMenuItem jMenuItemRegUsu;
    private javax.swing.JMenuItem jMenuItemSegUsu;
    private javax.swing.JMenu jMenuListas;
    private javax.swing.JMenu jMenuRegistros;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JTextField jRegisterApellidolField;
    private javax.swing.JTextField jRegisterEmailField;
    private javax.swing.JInternalFrame jRegisterFrame;
    private javax.swing.JTextField jRegisterNicknameField;
    private javax.swing.JTextField jRegisterNombreField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
